# 307 - Operadores para el Manejo de Errores

Por [Alan Badillo Salas](https://www.nomadacode.com)

## `onErrorReturn()`

> Si ocurre un error finaliza el flujo con un elemento personalizado final (en modo de función).

```java
Observable.error(new Exception("Error"))
    .onErrorReturn(throwable -> 0)
    .subscribe(System.out::println)
```

## `onErrorReturnItem()`

> Si ocurre un error finaliza el flujo con un elemento personalizado final.

```java
Observable.error(new Exception("Error"))
    .onErrorReturnItem(0)
    .subscribe(System.out::println)
```

## `onErrorResumeWith()`

> Si ocurre un error finaliza el flujo con los elementos de un segundo observador.

```java
Observable.error(new Exception("Error"))
    .onErrorResumeWith(Observable.just(1, 2, 3))
    .subscribe(System.out::println)
```

## `onErrorResumeNext()`

> Si ocurre un error finaliza el flujo con los elementos de un segundo observador (en modo de función).

```java
Observable.error(new Exception("Error"))
    .onErrorResumeNext(throwable -> Observable.just(4, 5, 6))
    .subscribe(System.out::println)
```

## `retry()`

> Si ocurre un error, vuelve a repetir las veces establecidas la toma del último elemento.

```java
Observable.just(1, 5, 0, 4, 2)
    .map(i -> {
        if (i == 0) throw new Exception("Error");
        return i;
    })
    .retry(3)
    .subscribe(
            System.out::println,
            throwable -> System.out.printf("ERROR: %s %n", throwable.getMessage())
    )
```
